CREATE TABLE `t_sys_user` (
      `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
      `user_name` varchar(50) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '用户名',
      `password` varchar(32) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '密码',
      `salt` varchar(20) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '密码盐',
      `name` varchar(50) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '姓名',
      `sex` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '性别:0-未知,1-男,2-女,9-其他',
      `email` varchar(200) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '电子邮箱',
      `mobile` varchar(15) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '手机号',
      `identity_card` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '身份证号',
      `is_admin` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '是否管理员:0-不是,1-是',
      `is_system` tinyint(3) NOT NULL DEFAULT '0' COMMENT '是否系统账号:0-不是,1-是',
      `status` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '状态:1-可用,2-禁用',
      `remark` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '备注',
      `last_pwd_update_time` datetime DEFAULT NULL COMMENT '上次更改密码时间',
      `is_del` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '是否已删除:1-是，0-否',
      `create_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '数据创建人ID',
      `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据创建时间',
      `create_ip` varchar(16) COLLATE utf8mb4_bin DEFAULT '' COMMENT '数据创建IP',
      `update_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '数据更新人ID',
      `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据更新时间',
      `update_ip` varchar(16) COLLATE utf8mb4_bin DEFAULT '' COMMENT '数据更新IP',
      PRIMARY KEY (`id`) USING BTREE,
      KEY `idx_user_name_password` (`user_name`,`password`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='系统用户信息表';